apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: survey-management-backend-hpa
  namespace: survey-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: survey-management-backend
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50