version: '3.8'

services:
  edition_db:
    build:
      context: ./new_Questionnaire_backend/appDB/edition_db  # 指向数据库 Dockerfile 的上下文
    image: my_edition_db
    container_name: my_edition_db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: edition_db
    ports:
      - "3301:3306"
    volumes:
      - db_edition_data:/var/lib/mysql
    networks:
      - mynetwork

  management_db:
    build:
      context: ./new_Questionnaire_backend/appDB/management_db  # 指向数据库 Dockerfile 的上下文
    image: my_management_db
    container_name: my_management_db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: management_db
    ports:
      - "3302:3306"
    volumes:
      - db_management_data:/var/lib/mysql
    networks:
      - mynetwork

  user_db:
    build:
      context: ./new_Questionnaire_backend/appDB/user_db  # 指向数据库 Dockerfile 的上下文
    image: my_user_db
    container_name: my_user_db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: user_db
    ports:
      - "3303:3306"
    volumes:
      - db_user_data:/var/lib/mysql
    networks:
      - mynetwork

  edition:
    build:
      context: ./new_Questionnaire_backend
      dockerfile: Dockerfile_edition
    image: my_edition_back
    container_name: my_edition_back
    environment:
      - DJANGO_DB_HOST=edition_db
      - DJANGO_DB_PORT=3306
      - DJANGO_DB_USER=root
      - DJANGO_DB_PASSWORD=123456
    depends_on:
      - edition_db
    ports:
      - "7002:8000"
    networks:
      - mynetwork

  management:
    build:
      context: ./new_Questionnaire_backend
      dockerfile: Dockerfile_management
    image: my_management_back
    container_name: my_management_back
    environment:
      - DJANGO_DB_HOST=management_db
      - DJANGO_DB_PORT=3306
      - DJANGO_DB_USER=root
      - DJANGO_DB_PASSWORD=123456
    depends_on:
      - management_db
    ports:
      - "7001:8000"
    networks:
      - mynetwork

  user:
    build:
      context: ./new_Questionnaire_backend
      dockerfile: Dockerfile_user
    image: my_user_back
    container_name: my_user_back
    environment:
      - DJANGO_DB_HOST=user_db
      - DJANGO_DB_PORT=3306
      - DJANGO_DB_USER=root
      - DJANGO_DB_PASSWORD=123456
    depends_on:
      - user_db
    ports:
      - "7000:8000"
    networks:
      - mynetwork

  front:
    build:
      context: ./Questionnaire  # 指向前端文件夹的上下文
    image: questionnaire-app
    container_name: questionnaire-app
    ports:
      - "1234:80"  # 示例端口，视前端应用而定
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  db_edition_data:
  db_management_data:
  db_user_data:
