apiVersion: apps/v1
kind: Deployment
metadata:
  name: questionnaire-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: questionnaire
  template:
    metadata:
      labels:
        app: questionnaire
    spec:
      containers:
      - name: questionnaire
        image: tiezhugiegie/questionnaire-app:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: questionnaire-service-test
spec:
  selector:
    app: questionnaire
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31235  # 您可以指定一个介于30000-32767之间的端口号
  type: NodePort