apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: zhiyi
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30001