apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-management-back
  namespace: zhiyi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-management-back
  template:
    metadata:
      labels:
        app: my-management-back
    spec:
      containers:
      - name: my-management-back
        image: my-management-back
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8000
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /ready
        #     port: 8000
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
