apiVersion: v1
kind: Service
metadata:
  name: my-management-back-service
  namespace: zhiyi
spec:
  type: NodePort
  selector:
    app: my-management-back
  ports:
  - name: http
    port: 7001
    targetPort: 8000
    nodePort: 31001
