apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-user-back
  namespace: zhiyi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-user-back
  template:
    metadata:
      labels:
        app: my-user-back
    spec:
      containers:
      - name: my-user-back
        image: my-user-back
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
        resources:
          requests:
            cpu: "150m"    # CPU 请求量
            memory: "256Mi"  # 内存请求量
          limits:
            cpu: "300m"    # CPU 限制量
            memory: "512Mi"  # 内存限制量


        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8000
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /ready
        #     port: 8000
        #   initialDelaySeconds: 5
        #   periodSeconds: 10git