apiVersion: v1
kind: Service
metadata:
  name: my-user-back-service
  namespace: zhiyi
spec:
  type: ClusterIP
  selector:
    app: my-user-back
  ports:
  - name: http
    port: 8000
    targetPort: 8000
