# Generated by Django 3.2 on 2024-08-21 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlankQuestion',
            fields=[
                ('QuestionID', models.AutoField(primary_key=True, serialize=False)),
                ('SurveyID', models.IntegerField(unique=True)),
                ('Text', models.TextField(max_length=500)),
                ('IsRequired', models.BooleanField(default=True)),
                ('QuestionNumber', models.IntegerField(default=0)),
                ('Score', models.IntegerField(blank=True, default=0, null=True)),
                ('Category', models.IntegerField()),
                ('CorrectAnswer', models.TextField(max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChoiceQuestion',
            fields=[
                ('QuestionID', models.AutoField(primary_key=True, serialize=False)),
                ('SurveyID', models.IntegerField(unique=True)),
                ('Text', models.TextField(max_length=500)),
                ('IsRequired', models.BooleanField(default=True)),
                ('QuestionNumber', models.IntegerField(default=0)),
                ('Score', models.IntegerField(blank=True, default=0, null=True)),
                ('Category', models.IntegerField()),
                ('MaxSelectable', models.IntegerField(default=1, null=True)),
                ('OptionCnt', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtherOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IsRequired', models.BooleanField(default=True)),
                ('Text', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='RatingQuestion',
            fields=[
                ('QuestionID', models.AutoField(primary_key=True, serialize=False)),
                ('SurveyID', models.IntegerField(unique=True)),
                ('Text', models.TextField(max_length=500)),
                ('IsRequired', models.BooleanField(default=True)),
                ('QuestionNumber', models.IntegerField(default=0)),
                ('Score', models.IntegerField(blank=True, default=0, null=True)),
                ('Category', models.IntegerField()),
                ('MinRating', models.IntegerField(default=1, null=True)),
                ('MinText', models.TextField(max_length=500, null=True)),
                ('MaxRating', models.IntegerField(default=5, null=True)),
                ('MaxText', models.TextField(max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('SubmissionID', models.AutoField(primary_key=True, serialize=False)),
                ('SurveyID', models.IntegerField(unique=True)),
                ('RespondentID', models.IntegerField(unique=True)),
                ('SubmissionTime', models.DateTimeField(auto_now_add=True)),
                ('Status', models.CharField(choices=[('Unsubmitted', 'Unsubmitted'), ('Submitted', 'Submitted'), ('Graded', 'Graded'), ('Deleted', 'Deleted')], max_length=20)),
                ('Score', models.IntegerField(blank=True, null=True)),
                ('Interval', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RatingAnswer',
            fields=[
                ('AnswerID', models.AutoField(primary_key=True, serialize=False)),
                ('Rate', models.IntegerField(blank=True, null=True)),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edition_project.ratingquestion')),
                ('Submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratinganswer_answers', to='edition_project.submission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChoiceOption',
            fields=[
                ('OptionID', models.AutoField(primary_key=True, serialize=False)),
                ('Text', models.CharField(max_length=200)),
                ('IsCorrect', models.BooleanField(default=False, null=True)),
                ('OptionNumber', models.IntegerField(default=0)),
                ('MaxSelectablePeople', models.IntegerField(default=-1)),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_options', to='edition_project.choicequestion')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceAnswer',
            fields=[
                ('AnswerID', models.AutoField(primary_key=True, serialize=False)),
                ('ChoiceOptions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edition_project.choiceoption')),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edition_project.choicequestion')),
                ('Submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choiceanswer_answers', to='edition_project.submission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlankAnswer',
            fields=[
                ('AnswerID', models.AutoField(primary_key=True, serialize=False)),
                ('Content', models.TextField(max_length=500)),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edition_project.blankquestion')),
                ('Submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blankanswer_answers', to='edition_project.submission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
