# Generated by Django 3.2 on 2024-08-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edition_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blankquestion',
            name='SurveyID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='choicequestion',
            name='SurveyID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ratingquestion',
            name='SurveyID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='submission',
            name='RespondentID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='submission',
            name='SurveyID',
            field=models.IntegerField(),
        ),
    ]
