# Generated by Django 3.2 on 2024-08-21 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('SubmissionID', models.AutoField(primary_key=True, serialize=False)),
                ('SurveyID', models.IntegerField(unique=True)),
                ('RespondentID', models.IntegerField(unique=True)),
                ('SubmissionTime', models.DateTimeField(auto_now_add=True)),
                ('Status', models.CharField(choices=[('Unsubmitted', 'Unsubmitted'), ('Submitted', 'Submitted'), ('Graded', 'Graded'), ('Deleted', 'Deleted')], max_length=20)),
                ('Score', models.IntegerField(blank=True, null=True)),
                ('Interval', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('SurveyID', models.AutoField(primary_key=True, serialize=False)),
                ('OwnerID', models.IntegerField(unique=True)),
                ('Title', models.CharField(max_length=200)),
                ('Description', models.TextField(blank=True, max_length=500)),
                ('Is_released', models.BooleanField(blank=True)),
                ('Is_open', models.BooleanField(default=True)),
                ('Is_deleted', models.BooleanField(default=False)),
                ('PublishDate', models.DateTimeField(null=True)),
                ('Category', models.IntegerField(default=0)),
                ('TotalScore', models.IntegerField(blank=True, null=True)),
                ('TimeLimit', models.IntegerField(blank=True, null=True)),
                ('IsOrder', models.BooleanField(default=True)),
            ],
        ),
    ]
