# Generated by Django 3.2 on 2024-08-26 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='RespondentID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='submission',
            name='SurveyID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='survey',
            name='OwnerID',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='RewardOffering',
            fields=[
                ('RewardID', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.TextField()),
                ('Zhibi', models.IntegerField()),
                ('AvailableQuota', models.IntegerField()),
                ('Survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='management_project.survey')),
            ],
        ),
    ]
