# Generated by Django 3.2 on 2024-08-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_project', '0002_auto_20240826_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='SubmissionTime',
            field=models.DateTimeField(null=True),
        ),
    ]
