# Generated by Django 3.2 on 2024-08-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_project', '0003_alter_submission_submissiontime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='PublishDate',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
