# Generated by Django 3.2 on 2024-08-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_project', '0004_alter_survey_publishdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='PublishDate',
            field=models.DateTimeField(null=True),
        ),
    ]
