FROM python:3.11

EXPOSE 8000

RUN mkdir /management -p

WORKDIR /management

ADD ./requirements.txt /management

RUN cd /management
RUN python3 -m pip install --upgrade pip -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install mysqlclient -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install cryptography==42.0.8 -i https://pypi.tuna.tsinghua.edu.cn/simple

ADD ./management /management

CMD ["python3", "manage.py", "runserver", "0:8000"]