apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-management-db
  namespace: zhiyi
spec:
  serviceName: "my-management-db"
  replicas: 1
  selector:
    matchLabels:
      app: my-management-db
  template:
    metadata:
      labels:
        app: my-management-db
    spec:
      containers:
      - name: my-management-db
        image: my-management-db
        imagePullPolicy: Never
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "standard"
      resources:
        requests:
          storage: 2Gi
