apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my_edition_db
  namespace: zhiyi
spec:
  serviceName: "my_edition_db_service"
  replicas: 1
  selector:
    matchLabels:
      app: my_edition_db
  template:
    metadata:
      labels:
        app: my_edition_db
    spec:
      containers:
      - name: my_edition_db
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql #容器内挂载位置
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi
