<<<<<<<< HEAD:for-docker-advanced/db/my-user-db-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-user-db
  namespace: zhiyi
spec:
  serviceName: "my-user-db"
  replicas: 1
  selector:
    matchLabels:
      app: my-user-db
  template:
    metadata:
      labels:
        app: my-user-db
    spec:
      containers:
      - name: my-user-db
        image: my-user-db
        imagePullPolicy: Never
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi
========
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my_user_db
  namespace: zhiyi
spec:
  serviceName: "my_user_db"
  replicas: 1
  selector:
    matchLabels:
      app: my_user_db
  template:
    metadata:
      labels:
        app: my_user_db
    spec:
      containers:
      - name: my_user_db
        image: my_user_db
        imagePullPolicy: Never
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi
>>>>>>>> 1cd2cac56bdff82b0ad25dd46d760c526cc14907:for-docker-advanced/db/my_user_db_statefulset.yaml
