apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: other-db
  namespace: zhiyi
spec:
  serviceName: "other-db"
  replicas: 1
  selector:
    matchLabels:
      app: other-db
  template:
    metadata:
      labels:
        app: other-db
    spec:
      containers:
      - name: other-db
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: #TODO root password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql #容器内挂载位置
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi
