apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: survey-db
  namespace: zhiyi
spec:
  serviceName: "survey-db"
  replicas: 1
  selector:
    matchLabels:
      app: survey-db
  template:
    metadata:
      labels:
        app: survey-db
    spec:
      containers:
      - name: survey-db
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: #TODO root password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "standard"
      resources:
        requests:
          storage: 2Gi
