name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  remote-build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: appleboy/ssh-action@master
        with:
          host: 82.156.88.4
          username: ubuntu
          password: BUaa2221
          key: ${{ secrets.SSH_KEY }}

      - name: Install Updates and Basic Tools
        uses: appleboy/ssh-action@master
        with:
          host: 82.156.88.4
          username: ubuntu
          password: BUaa2221
          key: ${{ secrets.SSH_KEY }}
          script: |
            if ! command -v git &> /dev/null; then
              echo "Git not found. Installing Git..."
              sudo apt-get update
              sudo apt-get install -y git
            fi

      - name: Install Docker
        uses: appleboy/ssh-action@master
        with:
          host: 82.156.88.4
          username: ubuntu
          password: BUaa2221
          key: ${{ secrets.SSH_KEY }}
          script: |
            if ! command -v docker &> /dev/null; then
              echo "Docker not found. Installing Docker..."
              sudo apt-get install -y docker.io
              sudo systemctl start docker
              sudo systemctl enable docker
            fi

      - name: Install Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: 82.156.88.4
          username: ubuntu
          password: BUaa2221
          key: ${{ secrets.SSH_KEY }}
          script: |
            if ! docker compose version &> /dev/null; then
              echo "docker-compose-plugin not found. Installing docker-compose-plugin..."
              sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
              sudo apt  install docker-compose 
            fi

      - name: Prepare Application Environment
        uses: appleboy/ssh-action@master
        with:
          host: 82.156.88.4
          username: ubuntu
          password: BUaa2221
          key: ${{ secrets.SSH_KEY }}
          script: |
            if [ -d "PaperWingsCarryingQuestions_Advanced" ]; then
              cd PaperWingsCarryingQuestions_Advanced
              git pull
            else
              git clone https://github.com/sweetlunar233/PaperWingsCarryingQuestions_Advanced.git
              cd PaperWingsCarryingQuestions_Advanced
            fi
            cd Questionnaire
            sudo npm install
            sudo npm run build
            cd ..
            
            sudo docker-compose build

            # sudo docker tag questionnaire-app tiezhugiegie/questionnaire-app
            # sudo docker tag my_edition_db tiezhugiegie/my_edition_db
            # sudo docker tag my_management_db tiezhugiegie/my_management_db
            # sudo docker tag my_user_db tiezhugiegie/my_user_db
            # sudo docker tag my_edition_back tiezhugiegie/my_edition_back
            # sudo docker tag my_management_back tiezhugiegie/my_management_back
            # sudo docker tag my_user_back tiezhugiegie/my_user_back

            # sudo docker push tiezhugiegie/questionnaire-app
            # sudo docker push tiezhugiegie/my_edition_db
            # sudo docker push tiezhugiegie/my_management_db
            # sudo docker push tiezhugiegie/my_user_db
            # sudo docker push tiezhugiegie/my_edition_back
            # sudo docker push tiezhugiegie/my_management_back
            # sudo docker push tiezhugiegie/my_user_back

            sudo kubectl create namespace zhiyi

            sudo kubectl apply -f ~/PaperWingsCarryingQuestions_Advanced/for-docker-advanced/front_deployment.yml
            sudo kubectl apply -f ~/PaperWingsCarryingQuestions_Advanced/for-docker-advanced/my_edition_back_deployment.yaml
            sudo kubectl apply -f ~/PaperWingsCarryingQuestions_Advanced/for-docker-advanced/my_management_back_deployment.yaml
            sudo kubectl apply -f ~/PaperWingsCarryingQuestions_Advanced/for-docker-advanced/my_user_back_deployment.yaml
            sudo kubectl apply -f ~/PaperWingsCarryingQuestions_Advanced/for-docker-advanced/db/my_edition_db_statefulset.yaml
            sudo kubectl apply -f ~/PaperWingsCarryingQuestions_Advanced/for-docker-advanced/db/my_management_db_statefulset.yaml
            sudo kubectl apply -f ~/PaperWingsCarryingQuestions_Advanced/for-docker-advanced/db/my_user_db_statefulset.yaml

            # sudo docker exec -it my_backend python manage.py test

          # # 部署到 Kubernetes
          # - name: Deploy to Kubernetes
          #   run: |
          #     kubectl apply -f k8s/  # 应用